# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/auditus',
                'doc_host': 'https://CarloLepelaars.github.io',
                'git_url': 'https://github.com/CarloLepelaars/auditus',
                'lib_path': 'auditus'},
  'syms': { 'auditus.core': { 'auditus.core.AudioArray': ('core.html#audioarray', 'auditus/core.py'),
                              'auditus.core.AudioArray.__getitem__': ('core.html#audioarray.__getitem__', 'auditus/core.py'),
                              'auditus.core.AudioArray.__init__': ('core.html#audioarray.__init__', 'auditus/core.py'),
                              'auditus.core.AudioArray.__len__': ('core.html#audioarray.__len__', 'auditus/core.py'),
                              'auditus.core.AudioArray.shape': ('core.html#audioarray.shape', 'auditus/core.py'),
                              'auditus.core.AudioArray.show': ('core.html#audioarray.show', 'auditus/core.py'),
                              'auditus.core.calc_ratio': ('core.html#calc_ratio', 'auditus/core.py'),
                              'auditus.core.get_features': ('core.html#get_features', 'auditus/core.py'),
                              'auditus.core.load_audio': ('core.html#load_audio', 'auditus/core.py'),
                              'auditus.core.resample': ('core.html#resample', 'auditus/core.py')}}}
