# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/auditus',
                'doc_host': 'https://CarloLepelaars.github.io',
                'git_url': 'https://github.com/CarloLepelaars/auditus',
                'lib_path': 'auditus'},
  'syms': {'auditus.core': {'auditus.core.foo': ('core.html#foo', 'auditus/core.py')}}}
