"""Audio Embeddings"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['AudioArray']

# %% ../nbs/00_core.ipynb 3
import numpy as np
from fastcore.all import *

# %% ../nbs/00_core.ipynb 6
class AudioArray(BasicRepr): 
    def __init__(self, a: np.array, sr: int): store_attr()
    def show(self): return Audio(self, rate=self.sr)
    @property
    def shape(self): return self.a.shape
    def __len__(self): return len(self.a)
    def __getitem__(self, idx): return self.a[idx]
